// Generated by CoffeeScript 1.6.3
(function() {
  var admin, alerts, app, config, db, debug, express, info, lib, multipart, obj, warn, _ref;

  config = require('./lib/config');

  lib = require('./lib');

  _ref = require('./lib/logger'), debug = _ref.debug, info = _ref.info, warn = _ref.warn;

  db = require('./lib/db');

  admin = require('./app/admin');

  alerts = require('./app/alerts');

  obj = require('./app/obj');

  multipart = require('connect-multiparty');

  express = require('express');

  app = express();

  app.configure(function() {
    app.set("views", __dirname + "/jade");
    app.set("view engine", 'jade');
    app.enable("trust proxy");
    app.use(express.favicon());
    app.use(express.compress());
    app.use(express.cookieParser());
    app.use(express.json());
    app.use(app.router);
    if (config.env === "development") {
      app.use('/inc', express["static"](__dirname + "/inc"));
      app.use(express.errorHandler({
        dumpExceptions: true,
        showStack: true
      }));
      app.locals.pretty = true;
      return app.locals.cache = false;
    } else {
      app.use('/inc', express["static"](__dirname + "/inc", {
        maxAge: 1 * 24 * 3600 * 1000
      }));
      app.use(express.errorHandler());
      app.locals.pretty = false;
      return app.locals.cache = true;
    }
  });

  app.get('/', function(req, res) {
    return res.render("main", {
      title: "Карта социальных объектов Иркутска"
    });
  });

  app.get("/obj/list", obj.list);

  app.get("/obj/pic", obj.pic);

  app.get("/admin/", function(req, res) {
    return res.render("admin/index");
  });

  app.get("/admin", function(req, res) {
    return res.redirect("/admin/");
  });

  app.get("/admin/groups/:type", admin.groups);

  app.get("/admin/groups", function(req, res) {
    return res.render("admin/groups");
  });

  app.post("/admin/groups", admin.groups_update);

  app.get("/admin/alerts", function(req, res) {
    return res.render("admin/alerts");
  });

  app.get("/admin/alerts/list", admin.alerts_list);

  app.post("/admin/alert/status", admin.alert_status);

  app.post("/admin/alert/respond", admin.alert_respond);

  app.post("/admin/obj", admin.obj_post);

  app.get("/admin/obj_list", admin.obj_list);

  app.get("/admin/pic", admin.pic);

  app.post("/admin/pic", multipart(), admin.pic_upload);

  app.get("/admin/reports", function(req, res) {
    return res.render("admin/reports");
  });

  app.post("/admin/reports", express.urlencoded(), admin.reports);

  app.get('/groups/:type', obj.groups);

  app.get('/alerts/', function(req, res) {
    return res.render("alerts", {
      title: "Общественный контроль"
    });
  });

  app.get('/alerts', function(req, res) {
    return res.redirect("/alerts/");
  });

  app.get('/alerts/list', alerts.list);

  app.post('/alerts/add', multipart(), alerts.add);

  app.get('/info', function(req, res) {
    return res.render("info");
  });

  app.all("/_trace", function(req, res) {
    var t;
    t = {
      ips: req.ips,
      ua: req.headers['user-agent'] || "?"
    };
    if (req.sess) {
      lib.set_if(t, 'sid', req.sess.sid);
      lib.set_if(t, 'uid', req.sess.get("user_id"));
      lib.set_if(t, 'login', req.sess.get("user_login"));
    }
    lib.set_if(t, 'param', req.body);
    info("trace", t);
    res.send(204, "");
    t.ts = new Date();
    return db.trace(t);
  });

  info("Listen - " + config.server.host + ":" + config.server.port);

  app.listen(config.server.port, config.server.host);

  lib.watch_file(__filename);

}).call(this);
