// Generated by CoffeeScript 1.10.0
(function() {
  var config, debug, fetch_data, info, ref, warn, x;

  x = typeof exports !== "undefined" && exports !== null ? exports : this;

  config = require('../lib/config');

  ref = require('../lib/logger'), debug = ref.debug, info = ref.info, warn = ref.warn;

  fetch_data = require('../app').fetch_data;

  x.t_js = function(req, res) {
    var st, st_list;
    res.header("Content-Type", "text/javascript");
    st = req.query.st || "";
    if (!st) {
      return res.send("");
    }
    res.header("Cache-Control", "no-cache, no-store, must-revalidate");
    res.header("Pragma", "no-cache");
    res.header("Expires", 0);
    st_list = [st];
    return fetch_data(st_list, function(data) {
      var clr, html, last, ref1, t;
      if (!(last = data != null ? (ref1 = data[st]) != null ? ref1.last : void 0 : void 0)) {
        return res.send("");
      }
      if (!last.t || isNaN(last.t)) {
        return res.send("");
      }
      t = Math.round(last.t);
      if (t > 0) {
        clr = "#a40";
      } else if (t < 0) {
        clr = "#04d";
      } else {
        clr = "#555";
      }
      html = ("<a href=\"http://meteo38.ru/\" style=\"color:" + clr + ";text-decoration:none;\">") + (t > 0 ? "+" + t : "" + t) + "&deg;</a>";
      return res.send("try{document.getElementById(\"meteo38_t_" + st + "\").innerHTML='" + html + "';}catch(err){};");
    });
  };

}).call(this);
