// Generated by CoffeeScript 1.7.1
(function() {
  var config, db, debug, info, lib, warn, x, _ref;

  x = typeof exports !== "undefined" && exports !== null ? exports : this;

  config = require('../lib/config');

  db = require('../lib/db');

  lib = require('../lib');

  _ref = require('../lib/logger'), debug = _ref.debug, info = _ref.info, warn = _ref.warn;

  x.t_js = function(req, res) {
    return res.send("nimp");
  };

}).call(this);
