// Generated by CoffeeScript 1.7.1
(function() {
  var DATA_FRESH, ST_FRESH, ST_ID_MAX_LEN, ST_LIST_MAX, db, debug, info, isArray, lib, warn, x, _ref;

  x = typeof exports !== "undefined" && exports !== null ? exports : this;

  ST_LIST_MAX = 20;

  ST_ID_MAX_LEN = 64;

  ST_FRESH = 7 * 24 * 3600 * 1000;

  DATA_FRESH = 2 * 3600 * 1000;

  isArray = require('util').isArray;

  db = require('../lib/db');

  lib = require('../lib');

  _ref = require('../lib/logger'), debug = _ref.debug, info = _ref.info, warn = _ref.warn;

  x.st_list_cleanup = function(s) {
    var t;
    if (!(s != null ? s.length : void 0)) {
      return [];
    }
    s = ("" + s).split(',').slice(0, ST_LIST_MAX);
    return (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = s.length; _i < _len; _i++) {
        t = s[_i];
        _results.push(t.replace(/[^0-9a-zA-Z\-_]/g, '').substring(0, ST_ID_MAX_LEN));
      }
      return _results;
    })();
  };

  x.fetch_sts = function(st_list, cb) {
    return db.coll_st().find({
      _id: {
        $in: st_list
      },
      pub: 1
    }, {
      _id: 1,
      title: 1,
      last: 1,
      descr: 1,
      addr: 1,
      ll: 1,
      trends: 1
    }).sort({
      title: 1
    }).toArray(function(err, data) {
      if (err) {
        warn("app.fetch_sts:", err);
        return cb([]);
      }
      return cb(data);
    });
  };

  x.fetch_data = function(st_list, cb) {
    return db.coll_st().find({
      _id: {
        $in: st_list
      },
      pub: 1,
      ts: {
        $gte: new Date(lib.now() - DATA_FRESH)
      }
    }, {
      _id: 1,
      last: 1,
      trends: 1
    }).toArray(function(err, data) {
      if (err) {
        warn("app.fetch_data:", err);
        return cb([]);
      }
      return cb(data);
    });
  };

  x.get_stlist = function(cb) {
    var fresh;
    fresh = lib.now() - ST_FRESH;
    return db.coll_st().find({
      pub: 1,
      ts: {
        $gte: new Date(fresh)
      }
    }, {
      _id: 1,
      title: 1,
      addr: 1,
      descr: 1,
      ll: 1
    }).sort({
      title: 1
    }).toArray(function(err, data) {
      if (err) {
        warn("app.st_list:", err);
        return cb([]);
      }
      return cb(data);
    });
  };

}).call(this);
