// Generated by CoffeeScript 1.10.0
(function() {
  var HOSTCONF_DIR, conf, hostconf, k, pack, path, v;

  HOSTCONF_DIR = "var";

  path = require('path');

  if (!process.env.NODE_ENV) {
    process.env.NODE_ENV = 'development';
  }

  pack = require(path.resolve(process.cwd(), "package.json"));

  conf = require(path.resolve(process.cwd(), "config.json"));

  conf.appname = pack.name;

  conf.version = pack.version;

  hostconf = require(path.resolve(process.cwd(), HOSTCONF_DIR, process.env.NODE_ENV + ".json"));

  for (k in hostconf) {
    v = hostconf[k];
    if (v === null) {
      delete conf[k];
    } else {
      conf[k] = v;
    }
  }

  console.log((conf.appname + " " + conf.version + " - config loaded - ") + (new Date().toISOString().replace(/T/, ' ').replace(/\.\d\d\dZ$/, '')));

  module.exports = conf;

}).call(this);
