// Generated by CoffeeScript 1.6.3
(function() {
  var NONCE_LENGTH, SESS_COLLECTION, SESS_COOKIE, SESS_IPS, SESS_MAXAGE, SESS_TMP, SESS_TS, Sess, db, debug, info, load, make_sid, util, warn, x, _ref;

  x = typeof exports !== "undefined" && exports !== null ? exports : this;

  SESS_COLLECTION = 'sess';

  SESS_COOKIE = "sid";

  SESS_MAXAGE = 365 * 24 * 3600 * 1000;

  SESS_IPS = "ips";

  SESS_TS = "ts";

  SESS_TMP = "tmp";

  NONCE_LENGTH = 10;

  util = require('./index');

  _ref = require('./logger'), debug = _ref.debug, info = _ref.info, warn = _ref.warn;

  db = require('../lib/db');

  make_sid = function() {
    var i;
    return (new Date()).getTime().toString(16) + "." + (((function() {
      var _i, _len, _ref1, _results;
      _ref1 = util.urandom(NONCE_LENGTH);
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        i = _ref1[_i];
        _results.push(('0' + i.toString(16)).slice(-2));
      }
      return _results;
    })()).join(''));
  };

  /*
  
  db.sess: 
    _id: "hex(ts).hex(rnd)"
    ts: lastmod_timestamp
    st: int(-1: inactive, 0: temporary, 1: persistent)
    kv: {uid: "..."}
  */


  Sess = (function() {
    function Sess(id, dat) {
      this.sid = id;
      this.data = dat;
      this.mk = null;
      this.fixed = false;
    }

    Sess.prototype.new_sid = function() {
      return this.sid = make_sid();
    };

    Sess.prototype.get = function(key, defval) {
      var _ref1;
      return (_ref1 = this.data[key]) != null ? _ref1 : defval;
    };

    Sess.prototype.set = function(key, val) {
      if (this.fixed) {
        warn("sess.set failed: " + key);
        return this;
      }
      if (this.mk == null) {
        this.mk = {};
        if (this.sid == null) {
          this.sid = make_sid();
        }
      }
      this.mk[key] = val != null;
      this.data[key] = val;
      return this;
    };

    return Sess;

  })();

  load = function(sid, cb) {
    return db.coll(SESS_COLLECTION).findOne({
      _id: sid
    }, {
      _id: 0
    }, function(err, data) {
      if (err != null) {
        warn("sess.load:", err);
      }
      if (!err && sid && (data != null)) {
        return cb(sid, data);
      } else {
        return cb(null, {});
      }
    });
  };

  x.middleware = function() {
    return function(req, res, next) {
      if (req.sess != null) {
        return next();
      }
      res.on("header", function() {
        var fset, k, opts, sess, unset, v, _ref1;
        sess = req.sess;
        if (!sess || !req.sess.mk) {
          return;
        }
        sess.set(SESS_IPS, req.ips).set(SESS_TS, new Date());
        sess.fixed = true;
        opts = {
          httpOnly: true
        };
        if (!sess.get(SESS_TMP)) {
          opts.maxAge = SESS_MAXAGE;
        }
        res.cookie(SESS_COOKIE, sess.sid, opts);
        fset = {};
        unset = {};
        _ref1 = sess.mk;
        for (k in _ref1) {
          v = _ref1[k];
          if (v) {
            fset[k] = sess.data[k];
          } else {
            unset[k] = 1;
          }
        }
        return db.coll(SESS_COLLECTION).update({
          _id: sess.sid
        }, {
          $set: fset,
          $unset: unset
        }, {
          upsert: true
        }, function(err, dat) {
          if (err != null) {
            return warn("sess.save: " + sess.sid, err);
          }
        });
      });
      return load(req.cookies[SESS_COOKIE], function(sid, data) {
        req.sess = new Sess(sid, data);
        return next();
      });
    };
  };

}).call(this);
